name: mishainfo_flutter_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cloud_firestore: ^3.4.6
  velocity_x: 3.5.1
  firebase_core: 1.21.1
  flutter_quill: ^5.4.2
  image_picker: 0.8.5+3
  firebase_storage: 10.3.7
  flutter_swipe_action_cell: ^3.0.4
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

